services:
  - type: web
    name: grocery-tracker
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install wheel setuptools
      python -m pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
    disk:
      name: uploads
      mountPath: /static/uploads
      sizeGB: 1 