services:
  - type: web
    name: grocery-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production
    domains:
      - groceryapp-3pz1.onrender.com
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /app/static/uploads
      sizeGB: 1 